---
- name: Add OS tag
  set_fact:
    filebeat_tags: "{{ filebeat_tags }} + [ '{{ ansible_distribution }}' ]"

- name: Install filebeat
  import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- name: Install filebeat
  import_tasks: rhel.yml
  when: ansible_os_family == "Red Hat"

- name: Install filebeat
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Create monitors.d
  file:
    path: "{{filebeat_config_dir}}/monitors.d"
    state: directory
  become: yes
  when: filebeat_use_central_management != true

- name: Enroll in central management if configure
  shell: "{{filebeat_config_dir}}/filebeat enroll {{filebeat_cm_url}} {{filebeat_cm_token}} --force"
  become: yes
  when: filebeat_use_central_management
